### ISSUE TITLE
Unit tests or code samples for node-homie ?

### ISSUE THREAD

**Issue by bcopy** [schaze/node-homie#1]
Hello,

Thanks a lot for this library.
I'm struggling to implement the deviceManager.query() examples (v0.9.24), as none of the MQTT updates I make on my settable property are received by the Observable.

Are there somewhere tests or code snippets to look at, that would put me on the right track ?

Thanks

Brice

**Comment by schaze** [comment]
Hi Brice,

glad to see the lib is useful.
I have used the lib to implement various projects so far.  Can you give me more details what you want to achieve or what exactly your problem is? I am sure I will be able to help you out.

Brgds,
Thomas

**Comment by bcopy** [comment]
Hi Thomas,

Thank you very much, that would be great.
I'm trying to make deviceManager.query() work, by reproducing exactly what is in the README :

```
devices.query({
    node: {
        id: 'info'
    },
    property: {
        id: 'command'
    }
}).pipe(
    takeUntil(onDestroy$)
).subscribe({
    next: proplist => {
        console.log('\n Info node property update : ');
        proplist.forEach(p => {
            console.log('Property: ', p.pointer, ' - ', p.value);
        });
    }
});
```

I receive a first notification when the property value is initiated, but after that, I receive nothing.
Maybe I can submit a gist as full example, but then again if you have other projects using the library, I could inspect them and try and understand what I'm missing,

Thanks a lot
Brice

**Comment by schaze** [comment]
Hi Brice,

ok, I see where the problem is.
The .query() Observable will only emit if there are new properties found that match the query or if the existing ones change or dissappear - not when their value changes. This method is solely meant to identify properties based on their attributes.
You do need to subscribe to the value$ observable of each property returned by the query in order to get updates.
The strength (very powerful) and weakness (steep learning curve) of the lib is its extensive usage of rxjs and reactive patterns.

The solution to your problem is actually in the next 2 examples in the readme.
|
v

> But what if we wanted to also be updated when any of the actual temperature values are changing? As an example we want to always display a list of all temperature properties whenever any temperature changes.

>
```typescript
// Query all properties below a weather node with id 'temperature'
// Subscribe to their value updates indiviually and emit a list of 
// all matched properties whenever any value of any matched property changes
devices.query({
    node: {
        id: 'weather'
    },
    property: {
        id: 'temperature'
    }
}).pipe(
    // unsubsribe on application exit
    takeUntil(onDestroy$),
    // filter out empty values
    filter(props => props.length > 0),
    // subscribe to value updates
    switchMap(props =>
        // combine latest values in a list of the following observables
        combineLatest(
            // map each property to its value$ observable
            props.map(prop =>
                // filter out empty and only update on changed values
                prop.value$.pipe(
                    // filter out empty values
                    filter(notNullish),
                    // only update on temperatue changes
                    distinctUntilChanged(),
                    // in the end, map back to the property itself
                    map(value =>
                        prop
                    ))
            )
        )
    )
).subscribe({
    next: poplist => {
        console.log('\nTemperature list: ');
        poplist.forEach(p => {
            console.log('Property: ', p.pointer, ' - ', p.value);
        });
    }
});
```
If you need more explanation for the code snipped let me know and I can try to give a more verbose description.
Also if you only need one property of one device instead of multiple I would suggest using the selectProperty method which is much more straight forward (see readme):

```typescript
// select temperature property for weather node of device leq0122770
devices.selectProperty('leq0122770/weather/temperature').pipe(
    // unsubsribe on application exit
    takeUntil(onDestroy$),
    // subscribe to value updates <-- THIS IS THE PART THAT ENSURES UPDATES ON VALUES ARE RECEIVED
    switchMap(property => property.value$),
    // filter out empty values
    filter(notNullish),
    // only update on temperatue changes
    distinctUntilChanged()
).subscribe({
    next: temp => {
        console.log('Temperature update - current value: ', temp)
    }
})


```

**Comment by schaze** [comment]
For more code examples you can check my homecontrol project: https://github.com/homie-homecontrol. However they are mainly configurable smarthome services and will most likely contain only limited straight forward examples from which you can learn from in the beginning.

**Comment by bcopy** [comment]
Thanks a lot, it's perfectly clear now !
